package ATM;

/**
 *
 * @author User
 */
public class Display extends javax.swing.JFrame {

    /** Creates new form Display */
    public Display() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtaDisplay = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(350, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 280));

        txtaDisplay.setColumns(20);
        txtaDisplay.setRows(5);
        txtaDisplay.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtaDisplay.setEnabled(false);
        txtaDisplay.setMaximumSize(new java.awt.Dimension(300, 200));
        txtaDisplay.setMinimumSize(new java.awt.Dimension(300, 200));
        txtaDisplay.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel2.add(txtaDisplay);

        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked
    public  void setDisplay(String str){
        txtaDisplay.setText(str);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea txtaDisplay;
    // End of variables declaration//GEN-END:variables

}
